baseURL: "https://fbc101.github.io/fbc-portfolio/"
languageCode: "en-us"
title: "Franci's Portfolio"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Franci's Portfolio"
  description: This site is Franci's personal portfolio, which contains work experience, projects, etc.
  # staticPath: ""  # The path to serve the static files from
  favicon: "./favduck.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Franci's Portfolio" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Franci Branda-Chen"
    subtitle: "Full Stack SWE"
    content: "As a Full Stack Software Engineer, I love the mix of creativity, problem-solving, and continuous learning that comes with the job. Working on both the front-end and back-end keeps things exciting and helps me understand the whole system. I find it incredibly rewarding to turn ideas into functional applications and take pride in seeing projects through from start to finish. Plus, collaborating with diverse teams exposes me to new ideas and perspectives, leading to more innovative solutions and motivating me to create user-friendly applications."
    image: ./images/pfp.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/uc?export=download&id=1-5N7Ub04NqpM6FK63pkp6kkRudcQZr_t"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/fbc101
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/fbc-francibrandachen/


  # About
  about:
    enable: true
    title: "About Me"
    image: "./images/mt.jpg"
    content: |-
      I am a rising senior with a major in Computer Science and minor in Data Science at the [University of Pennsylvania](https://www.upenn.edu/). I have an interest in web development, and
      recently in Android development. Outside of work, I enjoy rock climbing, ping pong, pickleball, biking, board games, video games, cooking, and many other things.

    skills:
      enable: true
      title: "Here is a few of my technical skills:"
      items:
        - "Java (Advanced)"
        - "JavaScript (Advanced)"
        - "TypeScript (Advanced)"
        - "Python (Beginner)" 
        - "React (Proficient)"
        - "Node "
        - "Express"
        - "SQL (Advanced)"
        - "APIs"
        - "AWS Products (S3, DymanoDB, CloudWatch, Lambda, etc)"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Software Developer Intern"
        company: "Amazon"
        companyUrl: "https://www.amazon.jobs/en/jobs/2481711/2024-software-dev-engineer-intern"
        date: "Jun 2023 - Aug 2023"
        content: |

          - Implemented new scalable feature within an API to update existing clients configurations
          - Worked with Amazon S3 and DynamoDB to store clients configurations
          - Added new unit tests for the feature with Mockito, achieving 99%-line coverage for the code review
          - Designed and implemented a search tab within the team's UX Dashboard with React, enabling internal clients and team members to query existing configurations.
          - Actively participated in daily standup meetings with my team, where I discussed the project progress and sought advice to overcome obstacles within my code
          - Used regex for pattern matching within API response

      - job: "Software Engineer Intern"
        company: "Capital One"
        companyUrl: "https://www.capitalonecareers.com/internship-programs"
        date: "Jun 2024 - present"
        info:
          enable: false
        content: |
          - Set up UI with Vue for an internal tool that is used by Capital One managers
          - Worked on a configuration file to deploy our application
          - Actively participated in daily stand-up meetings as part of the Agile software development process, ensuring effective communication and collaboration within the team.
          - Utilized tools such as JIRA to track progress, report issues, and manage tasks in line with Agile best practices
          - Collaborated in the design of API endpoints and structure of the backend


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Applied Science in Computer Science"
        school:
          name: "University of Pennsylvania - Philadelphia, PA"
          url: "https://www.upenn.edu/"
        date: "2021 - 2025"
        GPA: "3.44 / 4.0"
        content: |-
          Extracurricular Activities
            - Penn Climbing Club, Member
        featuredLink:
          enable: true
          name: "Unofficial Transcript"
          url: "https://drive.google.com/uc?export=download&id=1R-Ex1Aka-Cims7raR-GZquSk0nhDV3fa"
      - title: "Bachelor of Arts"
        school:
          name: "Central High School - Philadelphia, PA"
          url: "https://centralhs.philasd.org/"
        date: "2017 - 2021"
        GPA: "4.31 out of 4.0"
        featuredLink:
          enable: true
          name: "Transcript"
          url: "https://drive.google.com/uc?export=download&id=13mqOdbj870wJBBL369JYFGFrVr1KvgF8"
        content: |-
          Extracurricular Activities
            - Wrestling Team
            - Tennis JV

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Penn Course Search - Chrome Extension
        content: This extension aims to facilitate the query for a specific Penn course without having to open additional tabs.
        image: ./images/projects/PennCourseSearch.png
        featured:
          name: Download
          link: https://chromewebstore.google.com/detail/penn-course-search/ebepgdgiamijmmppoaobmbohijppaieo?authuser=0&hl=en
        badges:
          - "Javascript"
          - "React"
        links:
          - icon: fab fa-github
            url: https://github.com/fbc101/PennCourseChromeExtension

      - title: Scholar Streets
        content: ScholarStreets is a comprehensive platform designed to assist users, especially parents, in finding suitable schools, neighborhoods, and homes. Leveraging educational data and housing information, ScholarStreets provides tailored recommendations to meet the diverse needs of users.
        image: ./images/projects/ScholarStreetT1.png
        featured:
          name: Demo
          link: https://drive.google.com/file/d/1U_66K9Zgolf7DMDR83Meo1PEv57RHHiP/view
        badges:
          - "JavaScript"
          - "Node"
          - "Express"
          - "React"
          - "SQL"
          - "Google Maps API"
        links:
          - icon: fab fa-github
            url: https://github.com/hussainzs/ScholarStreets

      - title: Pennstagram - Instagram Lite
        content: Final project for Cloud Computing and Scaling class. This project is a lite version of Instagram with features such as- recommendations for posts and users with LangChain, likes, comments, friend requests, invitations for chats, profile changes, face matching with actors, etc. The Github repository is private since we used the University's credentials for AWS.
        image: ./images/projects/Pennstagram.png
        badges:
          - "Typescript"
          - "React"
          - "Node"
          - "Express"
          - "SQL"
          - "Apache Kafka"
          - "ChromaDB"
          - "Langchain"
          - "AWS (RDS, Amazon S3, EC2)"

  #Contact
  contact:
    enable: true
    title: "Contact"
    content: Feel free to reach out via gmail, or LinkedIn!
    btnName: Mail me
    btnLink: mailto:fbc101@seas.upenn.ed
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    socialNetworks:
      github: https://github.com/fbc101
      linkedin: https://www.linkedin.com/in/fbc-francibrandachen/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
